-- Run this script in the Supabase SQL Editor

-- 1. Create Users Table (Custom table for simplicity to match current mock data)
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('SEEKER', 'RECRUITER'))
);

-- 2. Create Jobs Table
CREATE TABLE jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  company TEXT NOT NULL,
  location TEXT NOT NULL,
  salary TEXT NOT NULL,
  experience TEXT NOT NULL,
  skills TEXT[] NOT NULL,
  description TEXT NOT NULL,
  posted_date DATE NOT NULL DEFAULT CURRENT_DATE,
  recruiter_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

-- 3. Create Applications Table
CREATE TABLE applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'APPLIED' CHECK (status IN ('APPLIED', 'SHORTLISTED', 'REJECTED', 'SELECTED')),
  applied_date DATE NOT NULL DEFAULT CURRENT_DATE,
  UNIQUE(user_id, job_id) -- A user can only apply once to a specific job
);

-- 4. Insert Initial Mock Data
-- Insert mock users
INSERT INTO users (name, email, password, role) VALUES 
('Alex Developer', 'alex@example.com', '1234', 'SEEKER'),
('Sarah HR', 'hr@techcorp.com', '1234', 'RECRUITER');

-- Insert mock jobs (assuming Sarah HR has id = 2)
INSERT INTO jobs (title, company, location, salary, experience, skills, description, posted_date, recruiter_id) VALUES 
('Frontend Developer', 'TechCorp', 'Pune, Maharashtra', '8-12 LPA', '2-4 years', ARRAY['React', 'TypeScript', 'Tailwind'], 'We are looking for a skilled frontend developer to join our fast-growing team.', '2024-03-01', 2),
('Backend Engineer', 'DataSystems', 'Bangalore, Karnataka', '15-20 LPA', '3-5 years', ARRAY['Java', 'Spring Boot', 'MySQL'], 'Join our core infrastructure team to build scalable microservices.', '2024-03-05', 2),
('Full Stack Java Dev', 'FinTech Solutions', 'Remote', '10-18 LPA', '1-3 years', ARRAY['Java', 'React', 'PostgreSQL'], 'Build next-generation banking software using Java and React.', '2024-03-10', 2);

-- Note: No applications inserted by default, they will be created through the UI.
